---
# Copyright (C) 2018 Expedia Inc.
# Licensed under the Apache License, Version 2.0 (the "License");

# This is a sample file

source-catalog:
  name: source-aws-data-warehouse
  hive-metastore-uris: thrift://ip-10-29-175-20.us-west-2.compute.internal:9083
replica-catalog:
  name: aws-data-warehouse
  hive-metastore-uris: thrift://ip-10-29-174-223.us-west-2.compute.internal:9083
event-receiver:
  message-reader-factory-class: com.hotels.shunting.yard.receiver.sqs.messaging.SqsMessageReaderFactory
  configuration-properties:
    com.hotels.shunting.yard.event.receiver.sqs.queue: https://sqs.us-west-2.amazonaws.com/440407435941/shuntingyard-simple
    com.hotels.shunting.yard.event.receiver.sqs.wait.time.seconds: 15